### PR TITLE
Moved the board creation to a tools directory

### PR DESCRIPTION
**Pull request by Wallkhan**

### CODE REVIEW

**Comment by Wallkhan** [comment]
Been doing a squash and merge but each time it brings the chain of commits back

**Comment by michaeljenkin** [comment]
Eh. No worries. Can look at it when I get back.

While I am away why not just do push’s into the main branch. 

Looks like there was a build done in the configuration directory. Remove from the main branch if not already, but it populated the .gitignore file Could clean that up.

Michael

**Comment by michaeljenkin** [comment]
squash and merge

**Comment by michaeljenkin** [comment]
argh.. squash and merge

**Pull request merged**
